#!/bin/bash
set -eu

ZAPCC_VERSION=$(docker run --rm ${IMAGE_NAME} --version | grep version | sed "s/.*version[ ]*\([0-9]*\.[0-9]*\).*/\1/"))
docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${ZAPCC_VERSION}
docker push ${DOCKER_REPO}:${ZAPCC_VERSION}

docker tag bionic ${DOCKER_REPO}:bionic-${ZAPCC_VERSION}
docker push ${DOCKER_REPO}:bionic-${ZAPCC_VERSION}
