name: Docker Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu-version:
          - latest
          - focal
          - bionic
          - xenial
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          build-args: UBUNTU_VERSION=${{ matrix.ubuntu-version }}
          push: true
          tags: srzzumix/zapcc:${{ matrix.ubuntu-version }}
      - name: Push to version tag
        env:
          DOCKER_TAG: ${{ matrix.ubuntu-version }}
          IMAGE_NAME: srzzumix/zapcc:${{ matrix.ubuntu-version }}
          DOCKER_REPO: srzzumix/zapcc
        run: |
          ./hooks/post_push
